### ISSUE TITLE
[1.20.1] Adding 1.0.3 in modPack grant StepAssist

### ISSUE THREAD

**Issue by drakray** [Shadows-of-Fire/Apothic-Attributes#1]
(walking up 1 block without jumping, vanilla autojump is off)
NeoForge 47.1.66
~316 mods

Is it intended, and is there a way to disable this?

**Comment by Shadows-of-Fire** [comment]
I'm not reproducing such an issue in isolation or in production - what is the reported value of your Step Height attribute?

**Comment by drakray** [comment]
I tried on a smallmod instance(17 modfiles), and I don't have  the step assist
There the value is 0.6
Small ModList: https://pastebin.com/hdfU6VsN

On my other instance, with 167 modfiles, I have StepAssist, and the Step Height value is 0.6 too
MC1.20.1, NeoForge 41.1.76
Here is the Large ModList: https://pastebin.com/sBYTw2eP

**Comment by Shadows-of-Fire** [comment]
Do you have Sniffer Plus installed?  Its currently shipping a bad mixin which causes auto step assist. See https://github.com/Shadows-of-Fire/Apotheosis/issues/982

**Comment by drakray** [comment]
Yes I use it, and removing it fixes the problem this.
I guess I'll do without it for the time being.
Thank you for your time and your good work on your awesome mods :D
