### ISSUE TITLE
Crashes During Startup Sequence 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [Shadows-of-Fire/Apothic-Attributes#10]
MC 1.20.1
Forge 47.2.1
Mod version: ApothicAttributes-1.20.1-1.2.0.jar

[crash report](https://mclo.gs/kSZcht0)

[debug](https://mclo.gs/jZxjrlk)

[latest](https://mclo.gs/t7YPPMB)

random error messages when it crashes so im unable to isolate what exactly is causing it but I do know that when I update to 1.20. of apothic attributes from 1.1.4 it crashes. when I downgrade back to 1.1.4 it works normally.

**Comment by BookerCatch** [comment]
Upgrade Placebo to 8.5.6 or above.
