### ISSUE TITLE
1.20.1 Startup crash - Placebo related

### ISSUE THREAD

**Issue by Chillaxichance** [Shadows-of-Fire/Apothic-Attributes#11]
MC 1.20.1
Forge 47.2.4
Mod versions: 
ApothicAttributes-1.20.1-1.2.0.jar
Placebo-1.20.1-8.5.6.jar
Apotheosis-1.20.1-7.0.5.jar

Game crashes on startup, resolved by reverting updates to Placebo and AttributesLib.

NoClassDefFoundError: dev/shadowsoffire/placebo/reload/TypeKeyed

[crash-2023-11-16_21.13.18-client.txt](https://github.com/Shadows-of-Fire/Apothic-Attributes/files/13387744/crash-2023-11-16_21.13.18-client.txt)

**Comment by Shadows-of-Fire** [comment]
This is caused by using the wrong placebo version for that version of AA.
