### ISSUE TITLE
[1.20.1] Config Option to disable Potion Tooltips

### ISSUE THREAD

**Issue by Diedntgo** [Shadows-of-Fire/Apothic-Attributes#17]
**Apothic Attributes:** ApothicAttributes-1.20.1-1.2.1

Is there a config option to disable the Potion Tooltips added by this mod? If not, would it be possible to create config options to do so?

![2024-02-06_22 11 03](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/64341357/40dfdb37-4d56-4058-8cac-2d97b634a91c)
![2024-02-06_22 11 09](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/64341357/f589b3e1-325e-4e49-9a3c-0d0ed6b44782)

**Comment by Shadows-of-Fire** [comment]
The latter (the gray unlocalized string) is only shown if advanced tooltips (f3+h) is enabled.

Its trivial to add a config for it though, not sure when I might get to it.

**Comment by ffuentesm** [comment]
I would also like that, as I am using Effect description mod, which adds potion description to all potions, including moded potions, and this causes a duplicated line on the base vanilla potions.

![image](https://github.com/Fuzss/effectdescriptions/assets/44974827/f9ad8458-40cd-4fb3-8986-9bc5788926a8) ![image](https://github.com/Fuzss/effectdescriptions/assets/44974827/a70da850-28a8-4406-9354-16241164b3bf)
![image](https://github.com/Fuzss/effectdescriptions/assets/44974827/eb7d0f28-7623-4a71-ae2c-669815d67877)
![image](https://github.com/Fuzss/effectdescriptions/assets/44974827/48453d2d-62aa-4f7c-a3ab-5cc5127ccfb7)

**Comment by lukenator115** [comment]
I would also like this to be implemented! A simple toggle in the config would be hugely appreciated

**Comment by ffuentesm** [comment]
I updated to 1.3.0 which should have the config to disable this, but I see no config file
![image](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/44974827/288d47db-2dcc-481a-a52d-7033be391958)

**Comment by Shadows-of-Fire** [comment]
The config file is located at `/config/attributeslib.cfg`.  That menu likely does not support the .cfg config format used by my mods.
