### ISSUE TITLE
[1.20.1] Going from Spectator to Creative makes you unable to fly.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Apothic-Attributes#2]
Title ^

Tested with just MC 1.20.1, Forge 47.1.3 & Apothic Attributes (v1.1.3) + Placebo (v8.3.7).

**-** Gbergz

**Comment by Shadows-of-Fire** [comment]
This is currently being discussed at https://github.com/Shadows-of-Fire/Apotheosis/issues/995
