### ISSUE TITLE
Crash on forge 1.20.1

### ISSUE THREAD

**Issue by Marius-jj** [Shadows-of-Fire/Apothic-Attributes#27]
Crashes when shooting arrow on entity. Crash says: Can't find attribute attributeslib:dodge_chance

https://pastebin.com/kTtUm0R7

**Comment by RoyalReject** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/1220

It's an issue with a mod not using forges attribute registry.

**Comment by Marius-jj** [comment]
Oh okay, thanks! Would you happen to know what mod causes it? Or is it the connector mod?

**Comment by RoyalReject** [comment]
No clue. It's not connector itself but one of the fabric mods you are using.

**Comment by Marius-jj** [comment]
Thanks for the answer anyways! Did some testing and so far it's only crashing when shooting at the mob Naga from the Better Nether mod, so might be that mod. Gonna do some more testing, but then i know to crate a issue on the fabric mod pages atleast!

**Comment by SiverDX** [comment]
that should theoretically be fixed on the  connector side 

maybe they haven't released it yet as a new update - make sure you're using the latest version otherwise ask them about this issue
