### ISSUE TITLE
Multiple instances of elytra flight cause an invalid tag

### ISSUE THREAD

**Issue by cool5554** [Shadows-of-Fire/Apothic-Attributes#28]
![image-5](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/160371970/9a56c580-d3b6-4ec4-be26-046165a6b2e0)

As shown above when an elytra has an elytra flight tag it causes it to be invailid

**Comment by Shadows-of-Fire** [comment]
2c1ef52c77ebbcf8b916a3c0d9ff155b2438ea34
