### ISSUE TITLE
Incompatbility with Obscure API (Armor Piercing does not work)

### ISSUE THREAD

**Issue by LynxGrimbane** [Shadows-of-Fire/Apothic-Attributes#32]
### The Issue

When Obscure API is installed, Attributelib's  _armor piercing_  effect **does not** function. I have tested this in multiple formats:
- Potion effect form (personal commision)
- Gems
- /attribute command 
- Adding it to equipment via /give command
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
With Obscure API, my Netherite Sword does not get any piercing.
![Armor Piercing](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/74229751/cb1f631d-6eba-47f6-9807-b6baec9a7a00)
![Huh](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/74229751/4b834213-8ab7-44a5-9311-d3d1698ab40e)

When uninstalled, my Netherite Sword deals the full 8 damage (as I set my armor piercing attribute to 31)
![Screenshot_13](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/74229751/53898b3a-7e08-484c-853c-0013495197b8)

**Comment by Shadows-of-Fire** [comment]
Obscure API is a closed-source all rights reserved mod.  No support is provided for these mods.  You can report this as a bug to them and ask them resolve it on their end.
