### ISSUE TITLE
Some values of attributes are too big to have enough space for GUI

### ISSUE THREAD

**Issue by YocyCraft** [Shadows-of-Fire/Apothic-Attributes#38]
![2024-08-28_16 05 21](https://github.com/user-attachments/assets/5d9a1e6e-8ce0-47a9-af11-0368b70a7c03)
![2024-08-28_16 05 32](https://github.com/user-attachments/assets/25341f46-1191-4935-9642-73c95dc21013)

The maximum value is 1.797e308, which has too many digits, and this value can't be fully shown on the screen with GUI scale set to largest.

**Comment by Shadows-of-Fire** [comment]
The GUI shows the specified max value - developers should not use `Double.MAX_VALUE` as an upper bound, following the precedent set by vanilla.
