### ISSUE TITLE
Incompatible with lithium

### ISSUE THREAD

**Issue by Boshigiri** [Shadows-of-Fire/Apothic-Attributes#50]
All attributes this mod added will be invalid

Only Lithium installed without other mods

**Comment by Boshigiri** [comment]
version:
lithium-neoforge-0.14.2-snapshot+mc1.21.1-build.90
ApothicAttributes-1.21.1-2.4.0
Placebo-1.21.1-9.5.4

**Comment by RoyalReject** [comment]
Share your logs where it's claiming attributes are invalid. But with how lithium works it might be a bug on their side.

**Comment by Boshigiri** [comment]
https://mclo.gs/hGPn4rx
Should I submit to Lithium?

**Comment by Boshigiri** [comment]
lithium have fixed this issue
