### ISSUE TITLE
levitation potion not crafting

### ISSUE THREAD

**Issue by Supertankkillz** [Shadows-of-Fire/Apothic-Attributes#51]
when crafting potion of levitation, nothing happens just at a standstill

**Comment by Shadows-of-Fire** [comment]
I'm not able to reproduce this issue. The recipe for the potion of levitation works as described. Do note you need to use the short (01:30) variant of Slow Falling to make the potion, not the long (04:00) one.

![](https://i.imgur.com/gSXyhh6.png)
